export const interviews = [
  {
    id: "INT-1001",
    candidate: "Joey Tribbiani",
    role: "Frontend Developer",
    interviewer: "Mansi Kakade",
    duration: "56 mins",
    score: 4.8,
    integrity: 96,
    status: "Completed",
    date: "24 Jun 2026",
  },
  {
    id: "INT-1002",
    candidate: "Ross Geller",
    role: "Backend Developer",
    interviewer: "Rahul Patil",
    duration: "48 mins",
    score: 4.4,
    integrity: 92,
    status: "Completed",
    date: "23 Jun 2026",
  },
  {
    id: "INT-1003",
    candidate: "Rachel Green",
    role: "UI Designer",
    interviewer: "Anita Sharma",
    duration: "Pending",
    score: 0,
    integrity: 0,
    status: "Scheduled",
    date: "26 Jun 2026",
  },
  {
    id: "INT-1004",
    candidate: "Monica Geller",
    role: "Python Developer",
    interviewer: "Ashish Kande",
    duration: "51 mins",
    score: 4.9,
    integrity: 99,
    status: "Completed",
    date: "21 Jun 2026",
  },
];